# Generated by Django 3.1.7 on 2021-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('dislike_users', models.ManyToManyField(related_name='dislikes', to='accounts.User')),
                ('like_users', models.ManyToManyField(related_name='likes', to='accounts.User')),
            ],
        ),
    ]
