# Generated by Django 3.1.7 on 2021-03-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislikes', to='board.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='like_users',
            field=models.ManyToManyField(related_name='likes', to='board.Person'),
        ),
    ]
